version: "3"

services:
  web:
    build: .
    container_name: "ecommerce-backend"
    command: "npm run dev"
    volumes:
      - .:/src
    ports:
      - "3200:3200"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
